apiVersion: v1
kind: Pod
metadata:
  name: mygoapp-pod3
  namespace: fightclub
  labels:
     app: go-webserver
spec:
  containers:
  - name: goapp
    image: ashwaniyadav/goapp:latest
    ports:
    - containerPort: 8083
    env:
      - name: APPPORT
        value: "8083"